/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pack;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;

/**
 *
 * @author danie
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    Culebra panel1;
    Thread hilo;
    Hilos recorrido;
    static int velocidad1=0;
    public static JLabel etiqueta;
    public static JLabel etiquetavelocidad;
    public static JLabel etiquetaMovimientos;
    public static JLabel tiempo;
    static int hora=0, minutos=0,segundos=0;
    static boolean correrHilo=true;
    static boolean hiloCorriendo=false;
    
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(Color.black);
        etiqueta=new JLabel("1");
        etiqueta.setBounds(575,285,100,30);
        etiqueta.setBackground(Color.white);
        etiqueta.setFont(new Font("Andale Mono",1,16));
        etiqueta.setForeground(Color.orange);
        add(etiqueta);
        
        etiquetavelocidad=new JLabel();
        etiquetavelocidad.setBounds(555,365,100,30);
        etiquetavelocidad.setBackground(Color.white);
        etiquetavelocidad.setFont(new Font("Andale Mono",1,16));
        etiquetavelocidad.setForeground(Color.orange);
        add(etiquetavelocidad);
        
        etiquetaMovimientos=new JLabel("0");
        etiquetaMovimientos.setBounds(575,200,100,30);
        etiquetaMovimientos.setBackground(Color.white);
        etiquetaMovimientos.setFont(new Font("Andale Mono",1,16));
        etiquetaMovimientos.setForeground(Color.orange);
        add(etiquetaMovimientos);
        
        tiempo=new JLabel("00:00:00");
        tiempo.setBounds(30,30,200,70);
        tiempo.setBackground(Color.white);
        tiempo.setFont(new Font("Andale Mono",1,25));
        tiempo.setForeground(Color.yellow);
        add(tiempo);
        
   
        
        panel1=new Culebra(350,12);
        panel1.setBounds(75,150,350,350);
        panel1.setOpaque(false);
        this.add(panel1);
        
        Panel fondo=new Panel(350,12);
        fondo.setBounds(75,150,350,350);
        this.add(fondo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonIzquierdo = new javax.swing.JToggleButton();
        botonDerecho = new javax.swing.JToggleButton();
        botonArriba = new javax.swing.JToggleButton();
        botonAbajo = new javax.swing.JToggleButton();
        botonComenzar = new javax.swing.JToggleButton();
        comboDificultad = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonIzquierdo.setText("Izquierdo");
        botonIzquierdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIzquierdoActionPerformed(evt);
            }
        });

        botonDerecho.setText("Derecho");
        botonDerecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDerechoActionPerformed(evt);
            }
        });

        botonArriba.setText("Arriba");
        botonArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArribaActionPerformed(evt);
            }
        });

        botonAbajo.setText("Abajo");
        botonAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbajoActionPerformed(evt);
            }
        });

        botonComenzar.setText("Comenzar");
        botonComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComenzarActionPerformed(evt);
            }
        });

        comboDificultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facil", "Medio", "Dificil" }));
        comboDificultad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboDificultadItemStateChanged(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 255, 255));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Tamaño de la Serpiente");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Intervalo de Tiempo");

        jLabel3.setBackground(new java.awt.Color(0, 255, 255));
        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Cantidad de Movimientos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(329, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonArriba, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(comboDificultad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(9, 9, 9)))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(botonComenzar)
                .addGap(18, 18, 18)
                .addComponent(comboDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(botonArriba)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAbajo)
                    .addComponent(botonDerecho))
                .addGap(130, 130, 130))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIzquierdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIzquierdoActionPerformed
        if(evt.getSource()==botonIzquierdo){
            panel1.cambiarDireccion("izquierda");
        }
    }//GEN-LAST:event_botonIzquierdoActionPerformed

    private void botonDerechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDerechoActionPerformed
        if(evt.getSource()==botonDerecho){
            panel1.cambiarDireccion("derecha");
        }
    }//GEN-LAST:event_botonDerechoActionPerformed

    private void botonArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArribaActionPerformed
        if(evt.getSource()==botonArriba){
            panel1.cambiarDireccion("arriba");
        }
    }//GEN-LAST:event_botonArribaActionPerformed

    private void botonAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbajoActionPerformed
        if(evt.getSource()==botonAbajo){
            panel1.cambiarDireccion("abajo");
        }
    }//GEN-LAST:event_botonAbajoActionPerformed

    private void botonComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComenzarActionPerformed
        if(evt.getSource()==botonComenzar){
        recorrido=new Hilos(panel1);
        hilo=new Thread(recorrido);
        hilo.start();
        if(hiloCorriendo==false){
            correrHilo=true;
            hiloCorriendo=true;
            iniciarHiloReloj();
        }
        
        }
    }//GEN-LAST:event_botonComenzarActionPerformed

    private void iniciarHiloReloj(){
        if(correrHilo==true){
            Reloj timer=new Reloj(tiempo);
            timer.start();  
        }
    }
    
    private void comboDificultadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboDificultadItemStateChanged
        if(evt.getSource()==comboDificultad){
            String seleccion=comboDificultad.getSelectedItem().toString();
            switch(seleccion){
            case "Facil":
                velocidad1=1;
                break;
            case "Medio":
                velocidad1=2;
                break;
            case "Dificil":
                velocidad1=3;
                break;
            }
        }
    }//GEN-LAST:event_comboDificultadItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonAbajo;
    private javax.swing.JToggleButton botonArriba;
    private javax.swing.JToggleButton botonComenzar;
    private javax.swing.JToggleButton botonDerecho;
    private javax.swing.JToggleButton botonIzquierdo;
    private javax.swing.JComboBox<String> comboDificultad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
